### ISSUE TITLE
BUG | visible is not changing on certain devices

### ISSUE THREAD

**Issue by louisgv** [luispuig/react-snaplist-carousel#22]
```
  const visible = useVisibleElements(
    { debounce: 10, ref: snapList },
    ([element]) => element,
  );
```
This does not work on Chrome for Android 10. The visible stays at 0 after either drag scroll or invoking `goToSnapItem`.

Interestingly, it also does not work on Windows 10 Secondary monitor (?). This is a very weird behavior:
+ On a Chrome instance, the visible updates properly on my primary monitor.
+ Drag the exact same Chrome instance to secondary monitor: visible is reset to 0, and does not change.

`visible` might need a revisit... maybe adding more event handlers? :-? ....

**Comment by louisgv** [comment]
Here's a reproduction:
https://codesandbox.io/s/still-bush-xf7bn?file=/pages/index.js

I found that if I tried to use the `width` property of the SnapList, it won't work. The width of the SnapList is the same as the width of its container :-?

**Comment by luispuig** [comment]
Hello @louisgv ,

Thanks for reporting a possible issue. I checked your code and I found a problem:

There HTML is a div 100% width, with a div 350 px width inside, with the SnapList carousel 250px width too. So the SnapList carousel width is 350px.

The SnapItem widths comes from its children (MyItem). MyItem is defined with a width of 60vw, which means 60% of the viewport (screen). The problem is that the SnapItems are bigger than the SnapList. The useVisibleElements fires when the  SnapItem is 100% visible in the SnapList viewport.

I share a possible change:
Make the SanapItem be 100% width and MyItem 60% width. 60% of the SanapItem width.

https://codesandbox.io/s/fervent-flower-458io?file=/pages/index.js

**Comment by louisgv** [comment]
@luispuig For some reason I'm seeing the same behavior in your new codepen, when I click next visible is not being updated :\ 

Is there a way to restrict the scrollList container to be a fixed width (350px)?

**Comment by louisgv** [comment]
I tested that codepen on both Windows 10 Chrome and Android 10 Chrome, visible stays at 0 in both case.

**Comment by luispuig** [comment]
Let me show you the GIF for https://codesandbox.io/s/fervent-flower-458io?file=/pages/index.js:

![May-29-2020 09-59-19](https://user-images.githubusercontent.com/24297787/83236174-62519680-a193-11ea-9fe6-b25eafb0c008.gif)

The SnapList is just a div and SnapItem are even just divs. You control their width as a normal div element using CSS. Just make sure that the children (SnapItem) are not bigger than the parent (SnapList).
